-- ============================================================================
-- Bonfire Newsletter — database schema (Supabase / Postgres)
-- ============================================================================
-- Run this ONCE on a fresh Supabase project (SQL Editor, or `supabase db`).
-- It recreates every table, security function, RLS policy and the image bucket.
-- It contains NO secrets — you generate your own API tokens at the bottom.
--
-- Mental model:
--   * The AI worker only ever calls the SECURITY DEFINER functions below,
--     gated by a token. It can read its brief-archive and SUBMIT a draft.
--     It CANNOT publish. Only a human (admin token) can move a draft to
--     'published'. That is the entire approval gate.
--   * The public (anon key) can read ONLY published issues (RLS). Drafts are
--     invisible. api_tokens is unreadable (RLS on, zero policies).
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. TABLES
-- ---------------------------------------------------------------------------

create table if not exists public.issues (
  id              uuid primary key default gen_random_uuid(),
  issue_date      date not null,
  newsletter      text not null default 'cloud',   -- 'cloud' | 'games'
  title           text,
  status          text not null default 'draft'
                    check (status in ('draft','pending','approved','published','rejected')),
  content_json    jsonb,        -- structured issue (English). The app renders this.
  content_json_cn jsonb,        -- structured issue (Chinese). Powers the /cn page.
  content_html    text,         -- legacy: some old issues stored raw HTML instead.
  submitted_by    text,
  approved_by     text,
  approved_at     timestamptz,
  published_at    timestamptz,
  review_note     text,
  created_at      timestamptz not null default now()
);

-- Dedup memory: every story URL ever published, so the AI never repeats one.
create table if not exists public.story_archive (
  id           uuid primary key default gen_random_uuid(),
  url          text unique not null,
  headline     text,
  source       text,
  covered_date date,
  issue_id     uuid references public.issues(id) on delete set null,
  newsletter   text
);

-- API tokens. One row per role. Values are generated by YOU (see step 6).
create table if not exists public.api_tokens (
  name  text primary key,       -- 'agent' | 'admin'
  token text not null
);

-- RECOMMENDED HARDENING (not in the original; safe to add on a fresh setup):
-- one issue per (newsletter, date). Prevents the two pipelines (see HANDOFF_HUMAN
-- §"Two pipelines") from silently creating duplicate rows for the same date.
-- alter table public.issues add constraint issues_newsletter_date_key
--   unique (newsletter, issue_date);

-- ---------------------------------------------------------------------------
-- 2. ROW-LEVEL SECURITY
-- ---------------------------------------------------------------------------
alter table public.issues        enable row level security;
alter table public.story_archive enable row level security;
alter table public.api_tokens    enable row level security;   -- ON, with NO policies → unreadable via the API.

-- Public may read ONLY published issues. Drafts/pending/approved stay invisible.
drop policy if exists "Public can read published issues" on public.issues;
create policy "Public can read published issues"
  on public.issues for select
  using (status = 'published');

-- story_archive has RLS on and NO public policy: it is read only through the
-- token-gated agent_get_archive() function below (SECURITY DEFINER bypasses RLS).

-- ---------------------------------------------------------------------------
-- 3. AGENT FUNCTIONS  (token = api_tokens where name='agent')
-- ---------------------------------------------------------------------------

-- Read every story covered in the last N days, for strict dedup.
create or replace function public.agent_get_archive(
  p_token text, p_newsletter text, p_days integer default 90
) returns table(headline text, url text)
language plpgsql security definer set search_path to 'public'
as $fn$
begin
  if not exists (select 1 from api_tokens where name='agent' and token=p_token) then
    raise exception 'unauthorized';
  end if;
  return query
    select sa.headline, sa.url from story_archive sa
    where sa.newsletter = p_newsletter
      and sa.covered_date >= (current_date - (p_days || ' days')::interval)
    order by sa.covered_date desc;
end $fn$;

-- Submit a finished issue for HUMAN APPROVAL. Always lands as 'pending'.
-- There is deliberately no publish path here — the agent cannot publish.
create or replace function public.agent_submit_draft(
  p_token text, p_newsletter text, p_issue_date date, p_title text,
  p_content jsonb, p_submitted_by text default 'ai-worker',
  p_content_cn jsonb default null
) returns uuid
language plpgsql security definer set search_path to 'public'
as $fn$
declare v_id uuid;
begin
  if not exists (select 1 from api_tokens where name='agent' and token=p_token) then
    raise exception 'unauthorized';
  end if;
  -- idempotent: replace any not-yet-published draft for this date
  delete from issues
   where issue_date=p_issue_date and newsletter=p_newsletter
     and status in ('draft','pending','rejected');
  insert into issues (issue_date, newsletter, title, status, content_json, content_json_cn, submitted_by)
  values (p_issue_date, p_newsletter, p_title, 'pending', p_content, p_content_cn, p_submitted_by)
  returning id into v_id;
  return v_id;   -- NEVER published.
end $fn$;

-- ---------------------------------------------------------------------------
-- 4. ADMIN FUNCTIONS  (token = api_tokens where name='admin')
-- ---------------------------------------------------------------------------

-- List issues for the review queue (pending first), with a story count.
create or replace function public.admin_list_issues(
  p_token text, p_newsletter text
) returns table(id uuid, issue_date date, title text, status text, submitted_by text, stories integer)
language plpgsql security definer set search_path to 'public'
as $fn$
begin
  if not exists (select 1 from api_tokens where name='admin' and token=p_token) then
    raise exception 'unauthorized';
  end if;
  return query
    select i.id, i.issue_date, i.title, i.status, i.submitted_by,
           (1 + coalesce((select count(*)::int
              from jsonb_array_elements(coalesce(i.content_json->'sections','[]'::jsonb)) s,
                   jsonb_array_elements(coalesce(s->'stories','[]'::jsonb))), 0))
    from issues i where i.newsletter = p_newsletter
    order by (i.status='pending') desc, i.issue_date desc;
end $fn$;

-- The human action. Move an issue between statuses. On 'published' (and only
-- then) the issue's story URLs are written into story_archive for dedup, so a
-- rejected draft never burns its URLs.
create or replace function public.admin_set_status(
  p_token text, p_issue_id uuid, p_status text,
  p_actor text default 'admin', p_note text default null
) returns text
language plpgsql security definer set search_path to 'public'
as $fn$
declare v_content jsonb; v_date date; v_news text;
begin
  if not exists (select 1 from api_tokens where name='admin' and token=p_token) then
    raise exception 'unauthorized';
  end if;
  if p_status not in ('pending','approved','published','rejected') then
    raise exception 'bad status %', p_status;
  end if;
  update issues set status = p_status, review_note = coalesce(p_note, review_note),
    approved_by  = case when p_status='approved'  then p_actor else approved_by  end,
    approved_at  = case when p_status='approved'  then now()   else approved_at  end,
    published_at = case when p_status='published' then now()   else published_at end
  where id = p_issue_id
  returning content_json, issue_date, newsletter into v_content, v_date, v_news;
  if v_content is null then raise exception 'issue not found'; end if;

  if p_status = 'published' then
    insert into story_archive (url, headline, source, covered_date, issue_id, newsletter)
    select q.s->>'url', q.s->>'headline', q.s->>'source', v_date, p_issue_id, v_news
    from ( select v_content->'top_story' as s
           union all
           select st as s from jsonb_array_elements(coalesce(v_content->'sections','[]'::jsonb)) sec,
                jsonb_array_elements(coalesce(sec->'stories','[]'::jsonb)) st ) q
    where q.s->>'url' is not null
    on conflict (url) do update set issue_id = excluded.issue_id, newsletter = excluded.newsletter;
  end if;
  return p_status;
end $fn$;

-- The agent/admin call these through PostgREST with the anon key, so anon needs EXECUTE.
-- The token check inside each function is the real gate.
grant execute on function public.agent_get_archive(text,text,integer)              to anon;
grant execute on function public.agent_submit_draft(text,text,date,text,jsonb,text,jsonb) to anon;
grant execute on function public.admin_list_issues(text,text)                      to anon;
grant execute on function public.admin_set_status(text,uuid,text,text,text)        to anon;

-- ---------------------------------------------------------------------------
-- 5. IMAGE STORAGE
-- ---------------------------------------------------------------------------
-- Public-read bucket, images only, 5 MB cap. The app serves resized/cropped
-- variants via Supabase's render/image transform (see site/lib/render-issue.js).
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('issue-images','issue-images', true, 5242880,
        array['image/png','image/jpeg','image/jpg','image/webp','image/gif'])
on conflict (id) do nothing;

drop policy if exists issue_images_anon_select on storage.objects;
create policy issue_images_anon_select on storage.objects
  for select using (bucket_id = 'issue-images');

-- KNOWN CONTAINED HOLE (see HANDOFF_HUMAN §"Before you go public"): this lets the
-- pipeline upload with the publishable/anon key. For production, replace this with
-- a service-role-only write (drop this policy, upload from a trusted server).
drop policy if exists issue_images_anon_insert on storage.objects;
create policy issue_images_anon_insert on storage.objects
  for insert with check (bucket_id = 'issue-images');

-- ---------------------------------------------------------------------------
-- 6. YOUR TOKENS  — generate fresh, do NOT reuse Bonfire's. Keep them secret.
-- ---------------------------------------------------------------------------
-- Generate two random tokens (e.g. `openssl rand -hex 24`) and insert them:
--   insert into api_tokens (name, token) values
--     ('agent', '<random-agent-token>'),
--     ('admin', '<random-admin-token>');
-- The agent token goes in the MCP server (mcp/.token). The admin token is used
-- only server-side by the admin/approval UI — never ship it to the browser.
